// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPgJjh9UmwGq5VisVpUFXH8W_pGNudICU',
    appId: '1:126687330758:web:722fc38560530d1cd772c7',
    messagingSenderId: '126687330758',
    projectId: 'growi-1',
    authDomain: 'growi-1.firebaseapp.com',
    databaseURL: 'https://growi-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'growi-1.firebasestorage.app',
    measurementId: 'G-ZDC7S2J3LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCURtL-kQ8Js-8ldCR24bvp2ZHuQkAuvk8',
    appId: '1:126687330758:android:258dbe6177d6a07ad772c7',
    messagingSenderId: '126687330758',
    projectId: 'growi-1',
    databaseURL: 'https://growi-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'growi-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJtfUtGX2c1qhyPwqKMmq-jbWTpFuySOE',
    appId: '1:126687330758:ios:3cf1b554b0881479d772c7',
    messagingSenderId: '126687330758',
    projectId: 'growi-1',
    databaseURL: 'https://growi-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'growi-1.firebasestorage.app',
    iosClientId: '126687330758-enaqbjdncmc9k7oln627adtbi7g5h5ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.growiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJtfUtGX2c1qhyPwqKMmq-jbWTpFuySOE',
    appId: '1:126687330758:ios:3cf1b554b0881479d772c7',
    messagingSenderId: '126687330758',
    projectId: 'growi-1',
    databaseURL: 'https://growi-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'growi-1.firebasestorage.app',
    iosClientId: '126687330758-enaqbjdncmc9k7oln627adtbi7g5h5ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.growiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPgJjh9UmwGq5VisVpUFXH8W_pGNudICU',
    appId: '1:126687330758:web:157ace76e04604c7d772c7',
    messagingSenderId: '126687330758',
    projectId: 'growi-1',
    authDomain: 'growi-1.firebaseapp.com',
    databaseURL: 'https://growi-1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'growi-1.firebasestorage.app',
    measurementId: 'G-LXJK5Q4NW8',
  );
}
